In [2]:
import pandas as pd
import numpy as np

In [3]:
happiness_2019=pd.read_excel(r'C:\Users\rutuj\OneDrive\Documents\Northeastern University MS in Data Analytics Engineering\5. Computation & Visualization\Project 1\2019_HI_Data.xlsx')
happiness_2020=pd.read_excel(r'C:\Users\rutuj\OneDrive\Documents\Northeastern University MS in Data Analytics Engineering\5. Computation & Visualization\Project 1\2020_Happiness_IndexData.xls')
#covid_deaths=pd.read_csv(r'')

In [4]:
happiness_2019.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.88) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.7689,7.829888,7.707912,2.713678,1.340243,1.587276,0.986145,0.595895,0.152708,0.392913
1,Denmark,7.6001,7.666658,7.533542,2.392891,1.383439,1.572595,0.996019,0.592356,0.252320,0.410473
2,Norway,7.5539,7.615639,7.492160,2.240764,1.487767,1.581548,1.028123,0.603500,0.271304,0.340884
3,Iceland,7.4936,7.613283,7.373917,2.400876,1.380163,1.623651,1.025653,0.590905,0.354356,0.117980
4,Netherlands,7.4876,7.542098,7.433102,2.392895,1.396020,1.521903,0.999314,0.557075,0.322440,0.297978

In [5]:
happiness_2020.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900826,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [9]:
df_2019_2020=pd.merge(happiness_2019[['Country','Happiness score']],happiness_2020['Ladder score'],left_on=happiness_2019['Country'],right_on=happiness_2020['Country name'],how='inner')

In [10]:
df_2019_2020.head()

         key_0      Country  Happiness score  Ladder score
0      Finland      Finland           7.7689        7.8087
1      Denmark      Denmark           7.6001        7.6456
2       Norway       Norway           7.5539        7.4880
3      Iceland      Iceland           7.4936        7.5045
4  Netherlands  Netherlands           7.4876        7.4489

In [12]:
df_2019_2020.rename(columns={'Happiness score':'Happiness score_2019','Ladder score':'Happiness score_2020'},inplace=True)

In [14]:
df_2019_2020['Difference']=df_2019_2020['Happiness score_2020']-df_2019_2020['Happiness score_2019']

In [16]:
df_2019_2020['Difference %']=(((df_2019_2020['Happiness score_2020']-df_2019_2020['Happiness score_2019'])/df_2019_2020['Happiness score_2019'])*100)

In [17]:
df_2019_2020.head()

,key_0,Country,Happiness score_2019,Happiness score_2020,Difference,Difference %
0,Finland,Finland,7.7689,7.8087,0.0398,0.512301
1,Denmark,Denmark,7.6001,7.6456,0.0455,0.598674
2,Norway,Norway,7.5539,7.4880,-0.0659,-0.872395
3,Iceland,Iceland,7.4936,7.5045,0.0109,0.145458
4,Netherlands,Netherlands,7.4876,7.4489,-0.0387,-0.516850

In [18]:
df_2019_2020.to_csv(r'C:\Users\rutuj\OneDrive\Documents\Northeastern University MS in Data Analytics Engineering\5. Computation & Visualization\Project 1\2019_2020_change.csv')